# Generated by Django 5.2.2 on 2025-06-11 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBookingDetails',
            fields=[
                ('flight_booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('One-way', 'One-way'), ('Two-way', 'Two-way')], max_length=10)),
                ('travel_from', models.CharField(max_length=100)),
                ('airline_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('preferred_departure_time', models.TimeField(blank=True, null=True)),
                ('preferred_return_time', models.TimeField(blank=True, null=True)),
                ('meal_preference', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Jain', 'Jain'), ('No Preference', 'No Preference')], max_length=15)),
                ('baggage_allowance_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='bookings.booking')),
            ],
        ),
    ]
