# Generated by Django 5.2.2 on 2025-06-11 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainBookingDetails',
            fields=[
                ('train_booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('journey_class', models.CharField(choices=[('Sleeper', 'Sleeper'), ('3rd Class', '3rd Class'), ('2nd Class', '2nd Class'), ('1st Class', '1st Class')], max_length=15)),
                ('preferred_departure_time', models.TimeField(blank=True, null=True)),
                ('preferred_arrival_time', models.TimeField(blank=True, null=True)),
                ('train_no_or_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_preference', models.CharField(blank=True, choices=[('Lower', 'Lower'), ('Upper', 'Upper'), ('No Preference', 'No Preference')], max_length=50, null=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='train_details', to='bookings.booking')),
            ],
        ),
    ]
