# Generated by Django 5.2.2 on 2025-06-11 18:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking', models.UUIDField()),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number (10-15 digits, optional +)', regex='^\\+?\\d{10,15}$')])),
                ('email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_grade', models.CharField(max_length=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passengers.department')),
            ],
        ),
    ]
